In [2]:
import numpy as np

#initialising a numpy ndarrays with 3 rows, 2 columns
X = np.zeros((3,2))
X

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
#by default, ndarrays are float64
X.shape,X.dtype

((3, 2), dtype('float64'))

In [9]:
#setting values to whole row
X[0,:] = 1
X

array([[1., 1.],
       [0., 0.],
       [0., 0.]])

In [12]:
#setting values to whole column
X[:,0]=2
X

array([[2., 1.],
       [2., 0.],
       [2., 0.]])

In [15]:
X = np.array([[1,2],[3,4],[5,6]])
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
x = np.array([10,20])
print(X.shape, x.shape)

X+x

(3, 2) (2,)


array([[11, 22],
       [13, 24],
       [15, 26]])

In [19]:
X*x

array([[ 10,  40],
       [ 30,  80],
       [ 50, 120]])

In [22]:
#matrix multiplication
x = x.T
result = X@x
result

array([ 50, 110, 170])

Indexing

In [24]:
X = np.random.rand(3,2)
X

array([[0.06082334, 0.95100148],
       [0.75881016, 0.55639461],
       [0.76289398, 0.77947949]])

In [26]:
X>0.5

array([[False,  True],
       [ True,  True],
       [ True,  True]])

In [27]:
X[X>0.5] = 1
X

array([[0.06082334, 1.        ],
       [1.        , 1.        ],
       [1.        , 1.        ]])